language: python

python:
  - '3.6'

install:
  - pip install coveralls

script:
  - nosetests --with-coverage --cover-package=mathparse

after_success:
  - coveralls

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  distributions: "sdist bdist_wheel"
  on:
      tags: true
