language: python

python:
  - '3.6'

install:
  - pip install -r dev-requirements.txt

script:
  - flake8
  - nosetests --with-coverage --cover-package=mathparse
  - sphinx-build -nW -b html ./docs/ ./build/

after_success:
  - coveralls

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  distributions: "sdist bdist_wheel"
  on:
      tags: true
